(in-package :utter-glib)

(defctype gpointer :pointer)
(defctype gchar :char)
(defctype guchar :unsigned-char)
(defctype gint :int)
(defctype guint :unsigned-int)
(defctype gshort :short)
(defctype gushort :unsigned-short)
(defctype glong :long)
(defctype gulong :ulong)
(defctype gint8 :int8)
(defctype guint8 :uint8)
(defctype gint16 :int16)
(defctype guint16 :uint16)
(defctype gint32 :int32)
(defctype guint32 :uint32)
(defctype gint64 :int64)
(defctype guint64 :uint64)
(defctype gboolean gint)
(defctype gfloat :float)
(defctype gdouble :double)
(defctype gsize :unsigned-long)
(defctype gssize :long)
(defctype goffset gint64)
(defctype gintptr (:pointer :long))
(defctype guintptr (:pointer :unsigned-long))
